
import type { Challenge } from './types';

export const challenges: Challenge[] = [
  {
    day: 1,
    week: 1,
    track: "Relationships",
    title: "The Mirror Check: Their Bullshit vs. Your Bullshit",
    description: "You Can't Control Them (Stop Trying)",
    quote: { 
      text: "Whenever you want to cheer yourself up, consider the good qualities of your companions, for instance, the energy of one, the modesty of another, the generosity of yet another. Nothing gives as much pleasure as the image of the virtues displayed in the character of our contemporaries.", 
      author: "Marcus Aurelius" 
    },
    broTranslation: "Stop obsessing over everyone's flaws and fuck-ups. Yeah, people are messy, inconsistent, and disappointing. But guess what? So are you. Marcus is saying: instead of keeping a mental scorecard of how everyone's failing you, start noticing what they're actually good at. Your girl's always late? Maybe she also always shows up when shit gets real. Your friend's terrible with money? Perhaps he'd also give you his last dollar. You're so busy cataloging disappointments that you're blind to the good stuff right in front of you.",
    challenge: "The Flip List: Pick your three most frustrating relationships right now. For each person:\n- Write their most annoying trait/behavior\n- Now write two genuine strengths they have (not backhanded compliments - real shit)\n- Write one time they came through when it mattered\n\nIf you can't think of strengths or good moments, that's data too. Maybe it's time to audit who's in your circle.",
    morningPrompt: "Today when someone irritates me, I'll pause and ask: What am I trying to control that isn't mine to control?",
    eveningPrompt: "Answer these three questions:\n1. Which expectation did I have of someone today that was actually unfair?\n2. When did I react to someone based on my mood, not their actual behavior?\n3. What relationship problem am I complaining about that I'm actively contributing to?",
    winsTitle: "One relationship I fostered today:"
  },
  {
    day: 2,
    week: 1,
    track: "Relationships",
    title: 'The Expectation Trap',
    description: "The Expectation Trap: Why Your Disappointment Is Your Fault",
    quote: { text: "When another blames you or hates you, or people voice similar criticisms, go to their souls, penetrate inside and see what sort of people they are. You will realize that there is no need to be racked with anxiety that they should hold any particular opinion about you.", author: "Marcus Aurelius" },
    broTranslation: "When someone's talking shit or coming at you sideways, don't defend yourself yet. First, look at who's talking. Are they miserable? Insecure? Fighting their own demons? Nine times out of ten, their beef with you is really beef with themselves. Stop losing sleep over opinions from people who can't even stand their own company. Their criticism says more about their inner chaos than your actual worth.",
    challenge: "The Source Check: Today, when someone criticizes you or pisses you off, before you react, write down: 1) What they said/did, 2) What might be going on in THEIR life, 3) Why this might not actually be about you. Practice seeing past the attack to the pain behind it.",
    morningPrompt: "Today I will remember that hurt people hurt people, and their reactions are about their inner state, not my worth.",
    eveningPrompt: "Answer these three questions:\n1. What criticism did I take personally today that was really about the other person's issues?\n2. When did I create disappointment by expecting someone to act differently than they always do?\n3. How did my ego make a relationship moment harder than it needed to be?",
    winsTitle: "One expectation I released today:"
  },
  {
    day: 3,
    week: 1,
    track: "Relationships",
    title: "Boundaries Aren't Walls: The Art of Loving from a Distance",
    description: "Boundaries Aren't Walls: The Art of Loving from a Distance",
    quote: { text: "It is not death that a man should fear, but never beginning to live.", author: "Marcus Aurelius" },
    broTranslation: "You're so scared of losing people that you're not even living authentically around them. You bite your tongue, swallow your needs, and play nice to keep the peace. But here's the thing: keeping toxic people happy is a form of death. You're killing your real self to maintain fake relationships. Sometimes the most loving thing you can do - for you AND them - is create distance.",
    challenge: "The Energy Audit: List every person you interacted with today. Next to each name, put a '+' if they gave you energy, a '-' if they drained you, or '0' if neutral. Look at the pattern. Who consistently drains you? That's where you need boundaries.",
    morningPrompt: "Today I will say 'no' to one request that I would normally say yes to out of guilt or obligation.",
    eveningPrompt: "Answer these three questions:\n1. Where did I abandon my own needs to keep someone else comfortable?\n2. What boundary do I keep talking about setting but never actually enforce?\n3. When did protecting someone's feelings become more important than protecting my peace?",
    winsTitle: "One boundary I enforced today:"
  },
  {
    day: 4,
    week: 1,
    track: "Relationships",
    title: "The Victim Olympics: Stop Competing for Who Has It Worse",
    description: "The Victim Olympics: Stop Competing for Who Has It Worse",
    quote: { text: "How much trouble he avoids who does not look to see what his neighbor says or does.", author: "Marcus Aurelius" },
    broTranslation: "You're wasting so much energy tracking everyone else's bullshit. Who's getting more attention, who has it easier, who's getting away with what. Meanwhile, you're standing still, rotting in resentment. Every minute you spend being bitter about their advantages is a minute you're not building your own. Their journey isn't your journey. Eyes on your own paper.",
    challenge: "The Comparison Detox: Every time you catch yourself comparing your relationship/situation to someone else's today, stop and write down: 'Their story isn't my story.' Then write one thing you're grateful for in YOUR situation that you've been overlooking.",
    morningPrompt: "Today I will catch myself before I say 'must be nice' or any variation of victim-speak about others' relationships.",
    eveningPrompt: "Answer these three questions:\n1. When did jealousy or comparison poison my mood about my own relationships today?\n2. What story did I tell myself about being a victim that kept me from taking action?\n3. How did focusing on what others have blind me to what I already possess?",
    winsTitle: "One comparison I avoided today:"
  },
  {
    day: 5,
    week: 1,
    track: "Relationships",
    title: "The Apology Problem: When Sorry Becomes Your Default Setting",
    description: "The Apology Problem: When Sorry Becomes Your Default Setting",
    quote: { text: "The best revenge is not to be like your enemy.", author: "Marcus Aurelius" },
    broTranslation: "Stop apologizing for existing. You say sorry when you're not wrong, sorry for having needs, sorry for taking up space. You've become so focused on keeping everyone comfortable that you've made yourself small. But here's what's fucked: when you over-apologize, you train people to treat you as less than. The best response to people who make you feel small isn't to shrink - it's to stand firm in who you are.",
    challenge: "The Sorry Count: Carry a notecard today. Make a mark every time you apologize. At the end of the day, circle the ones where you were ACTUALLY wrong. The rest? That's your people-pleasing showing.",
    morningPrompt: "Today I will not apologize unless I've actually done something wrong. I'll replace 'sorry' with 'thank you' when appropriate.",
    eveningPrompt: "Answer these three questions:\n1. What did I apologize for today that wasn't actually my fault?\n2. When did I make myself smaller to make someone else feel bigger?\n3. Where am I accepting treatment I don't deserve because I think I need to earn basic respect?",
    winsTitle: "One unnecessary apology I avoided:"
  },
  {
    day: 6,
    week: 1,
    track: "Relationships",
    title: "The Mind Reader Delusion: They Can't Know What You Don't Say",
    description: "The Mind Reader Delusion: They Can't Know What You Don't Say",
    quote: { text: "We have two ears and one mouth so that we can listen twice as much as we speak.", author: "Epictetus" },
    broTranslation: "You're pissed because they 'should just know' what you need. But you never actually told them. You drop hints, give looks, and then rage when they don't get it. News flash: people aren't psychic. Your partner, friends, family - they're all stumbling through life just like you. Stop punishing people for not reading your mind and start using your words like an adult.",
    challenge: "The Direct Line: Identify one thing you've been hoping someone would 'just understand' without you saying it. Today, tell them directly. No hints, no passive aggression. Just: 'I need X' or 'It would mean a lot if Y.'",
    morningPrompt: "Today I will ask for what I need clearly instead of hoping people will figure it out.",
    eveningPrompt: "Answer these three questions:\n1. What resentment am I holding about something I never actually communicated?\n2. When did I expect someone to know my feelings without expressing them?\n3. Where did my fear of being direct create unnecessary relationship drama?",
    winsTitle: "One need I clearly communicated:"
  },
  {
    day: 7,
    week: 1,
    track: "Relationships",
    title: "The Forgiveness Hack: It's Not About Them",
    description: "The Forgiveness Hack: It's Not About Them",
    quote: { text: "The best way to avenge yourself is to not be like that.", author: "Marcus Aurelius" },
    broTranslation: "You're carrying grudges like trophies, thinking your anger is punishing them. Plot twist: they're sleeping fine while you're up at 3 AM replaying the betrayal. Forgiveness isn't saying what they did was okay. It's saying you're not going to let it poison another day of your life. You forgive to free yourself, not them. They might not deserve peace, but you do.",
    challenge: "The Release Write: Write a letter to someone you're struggling to forgive. Pour it all out - the anger, hurt, everything. Then burn it or tear it up. Don't send it. This is about releasing the poison from your system, not getting a response.",
    morningPrompt: "Today I will stop rehearsing old arguments in my head and poisoning my present with past hurts.",
    eveningPrompt: "Answer these three questions:\n1. What grudge am I holding that's hurting me more than the person I'm angry at?\n2. How did dwelling on past betrayals affect my ability to be present today?\n3. When did I punish someone in my mind for something they don't even know I'm still angry about?",
    winsTitle: "One grudge I chose to release:"
  },
  {
    day: 8,
    week: 2,
    track: "Relationships",
    title: "The Savior Complex: You're Not Their Hero (And That's Okay)",
    description: "The Savior Complex: You're Not Their Hero (And That's Okay)",
    quote: { text: "Don't demand that things happen as you wish, but wish that they happen as they do happen, and you will go on well.", author: "Epictetus" },
    broTranslation: "You're exhausting yourself trying to fix everyone. Their problems, their decisions, their lives. You think you're helping, but you're actually robbing them of their own growth and driving yourself insane. People need to face their own consequences to learn. Stop playing God. You can't save people who don't want to be saved, and honestly, it's arrogant to think you know what's best for everyone.",
    challenge: "The Fix-It Fast: Today, when someone comes to you with a problem, JUST LISTEN. Don't offer solutions unless they specifically ask. Count how many times you bite your tongue to stop from giving unsolicited advice. That's your savior complex talking.",
    morningPrompt: "Today I will let people own their problems without making them mine to solve.",
    eveningPrompt: "Answer these three questions:\n1. Where did I try to rescue someone from consequences they need to experience?\n2. What problem did I make mine that was never my responsibility?\n3. How did trying to control someone else's journey distract me from my own?",
    winsTitle: "One problem I didn't try to solve:"
  },
  {
    day: 9,
    week: 2,
    track: "Relationships",
    title: "The Attention Economy: Stop Begging for What Should Be Freely Given",
    description: "The Attention Economy: Stop Begging for What Should Be Freely Given",
    quote: { text: "If you want to improve, be content to be thought foolish and stupid with regard to external things.", author: "Epictetus" },
    broTranslation: "You're doing backflips trying to get noticed, appreciated, loved. Posting for likes, texting first always, being extra just to get a crumb of validation. But real talk: the right people don't make you perform for their attention. Stop auditioning for people who should already see your value. The moment you stop needing their validation is the moment you become truly powerful.",
    challenge: "The Attention Audit: Today, don't initiate contact with anyone you're always reaching out to first. See who notices. See who reaches out. That's your real circle. The silence will teach you everything.",
    morningPrompt: "Today I will not chase anyone's attention or beg for what should be freely given.",
    eveningPrompt: "Answer these three questions:\n1. Where did I perform for attention instead of being authentic?\n2. What validation did I seek externally that I should be giving myself?\n3. Who am I giving VIP treatment to while they treat me like an option?",
    winsTitle: "One moment I chose authenticity over attention:"
  },
  {
    day: 10,
    week: 2,
    track: "Relationships",
    title: "The Truth Debt: What You're Not Saying Is Killing Your Relationships",
    description: "The Truth Debt: What You're Not Saying Is Killing Your Relationships",
    quote: { text: "If anyone tells you that a certain person speaks ill of you, do not make excuses about what is said of you but answer, 'He was ignorant of my other faults, else he would not have mentioned these alone.'", author: "Epictetus" },
    broTranslation: "You're so busy being 'nice' that you've become fake. You swallow truths, hide your real opinions, and then wonder why your relationships feel hollow. People can sense when you're not being real, even if they can't name it. Your fake niceness is actually more disrespectful than honest disagreement. At least truth gives them something real to work with.",
    challenge: "The Truth Test: Have one uncomfortable but necessary conversation today. That thing you've been avoiding saying? Say it. With kindness, but say it. Stop letting important truths rot inside you.",
    morningPrompt: "Today I will speak my truth even if my voice shakes, rather than keeping peace at the cost of authenticity.",
    eveningPrompt: "Answer these three questions:\n1. What truth did I swallow today to avoid conflict?\n2. Where did my need to be liked override my need to be honest?\n3. How is my fear of confrontation slowly poisoning my relationships?",
    winsTitle: "One truth I spoke today:"
  },
  {
    day: 11,
    week: 2,
    track: "Relationships",
    title: "The Scoreboard Mentality: Love Isn't a Transaction",
    description: "The Scoreboard Mentality: Love Isn't a Transaction",
    quote: { text: "It never ceases to amaze me: we all love ourselves more than other people, but care more about their opinion than our own.", author: "Marcus Aurelius" },
    broTranslation: "You're keeping score. Who texted last, who paid more, who said 'I love you' first. You've turned relationships into spreadsheets. But here's what's fucked: real love doesn't count. When you're tallying who does more, you've already lost. Either give freely or don't give at all. This 50/50 bullshit is why your relationships feel like business deals.",
    challenge: "The Score Surrender: Do something nice for someone today WITHOUT mentioning it, posting about it, or expecting anything back. Feel how different it hits when you give without keeping score.",
    morningPrompt: "Today I will give without tracking what I get back.",
    eveningPrompt: "Answer these three questions:\n1. Where was I keeping score in my relationships today?\n2. What did I do expecting recognition or reciprocation?\n3. How does tracking who 'owes' who poison my ability to love freely?",
    winsTitle: "One act of unconditional giving:"
  },
  {
    day: 12,
    week: 2,
    track: "Relationships",
    title: "The Projection Game: You Hate in Others What You Hate in Yourself",
    description: "The Projection Game: You Hate in Others What You Hate in Yourself",
    quote: { text: "Whenever you are about to find fault with someone, ask yourself the following question: What fault of mine most nearly resembles the one I am about to criticize?", author: "Marcus Aurelius" },
    broTranslation: "That thing that drives you absolutely insane about them? Yeah, that's you. The arrogance you can't stand, the neediness that disgusts you, the flakiness that pisses you off - it's all mirror work. We despise most violently what we recognize in ourselves. Before you go off about their shortcomings, check if you're really just mad at your own reflection.",
    challenge: "The Mirror Check: Write down the three traits you hate most in others. Now, brutally honestly, write one way YOU display each of these traits (you do, even if it's subtle). Sit with that discomfort.",
    morningPrompt: "Today when I judge someone, I'll pause and ask: 'How am I guilty of the same thing?'",
    eveningPrompt: "Answer these three questions:\n1. What criticism of others was actually a criticism of myself?\n2. When did someone's behavior trigger me because it reminded me of my own patterns?\n3. What quality do I condemn in others that I secretly fear exists in me?",
    winsTitle: "One projection I recognized in myself:"
  },
  {
    day: 13,
    week: 2,
    track: "Relationships",
    title: "The Silence Treatment: When Nothing Is the Most Powerful Response",
    description: "The Silence Treatment: When Nothing Is the Most Powerful Response",
    quote: { text: "How much more grievous are the consequences of anger than the causes of it.", author: "Marcus Aurelius" },
    broTranslation: "You think you need the last word. You think you need to defend yourself, clap back, set the record straight. But most of the time? Your response causes more damage than their initial attack. Some people are trying to drag you into their chaos. Your power move isn't a better comeback - it's refusing to play. Silence isn't weakness; it's selective engagement.",
    challenge: "The No-Response Response: Today, when someone tries to bait you into an argument or sends that text designed to trigger you, don't respond for at least 4 hours. If after 4 hours it still needs addressing, then respond. Most of the time, it won't.",
    morningPrompt: "Today I will remember that not every action requires my reaction.",
    eveningPrompt: "Answer these three questions:\n1. What argument did I engage in that I could have simply walked away from?\n2. When did my need to be right cost me my peace?\n3. How did responding in anger make a situation worse instead of better?",
    winsTitle: "One argument I chose not to engage in:"
  },
  {
    day: 14,
    week: 2,
    track: "Relationships",
    title: "The Abandonment Hustle: Stop Leaving Before You're Left",
    description: "The Abandonment Hustle: Stop Leaving Before You're Left",
    quote: { text: "What brings no benefit to the hive brings none to the bee.", author: "Marcus Aurelius" },
    broTranslation: "You're so scared of being abandoned that you abandon first. You pull away when things get too good, sabotage when someone gets too close, ghost before you can be ghosted. You think you're protecting yourself, but you're just guaranteeing the loneliness you're trying to avoid. Your fear of being left is making you unloveable, not your actual flaws.",
    challenge: "The Stay Challenge: Identify one relationship where you're pulling away out of fear, not genuine issues. Today, lean IN instead. Send that text, make that plan, be vulnerable. Feel the discomfort of staying when your pattern is to run.",
    morningPrompt: "Today I will stay present in relationships instead of creating distance to avoid potential hurt.",
    eveningPrompt: "Answer these three questions:\n1. Where did I create distance today out of fear rather than genuine incompatibility?\n2. How did my fear of abandonment cause me to abandon first?\n3. What relationship am I sabotaging because it's getting 'too real'?",
    winsTitle: "One time I leaned in instead of pulling away:"
  },
  {
    day: 15,
    week: 3,
    track: "Relationships",
    title: "The Resentment Factory: When You Give to Get, Everyone Loses",
    description: "The Resentment Factory: When You Give to Get, Everyone Loses",
    quote: { text: "Be like the rocky headland on which the waves constantly break. It stands firm, and round it the seething waters are laid to rest.", author: "Marcus Aurelius" },
    broTranslation: "You do nice things, but with strings attached. You give, but you're secretly keeping tabs. Then you're shocked and bitter when people don't reciprocate the way you expected. But here's the truth: you weren't being generous, you were making investments. Real generosity expects nothing back. If you're giving to get, you're just manipulating with extra steps.",
    challenge: "The String Cutter: List three things you've done for others recently that you're low-key resentful about. Admit to yourself: were you truly giving, or were you investing? Today, mentally release any expectation of return on those 'investments.'",
    morningPrompt: "Today I will give only what I can afford to lose without resentment.",
    eveningPrompt: "Answer these three questions:\n1. What 'generous' act was actually a covert contract expecting something in return?\n2. Where did I create resentment by having unexpressed expectations?\n3. How did my conditional giving poison a relationship today?",
    winsTitle: "One act of giving without expectation:"
  },
  {
    day: 16,
    week: 3,
    track: "Relationships",
    title: "The Change Fantasy: They're Not a Project",
    description: "The Change Fantasy: They're Not a Project",
    quote: { text: "Don't explain your philosophy. Embody it.", author: "Epictetus" },
    broTranslation: "You're dating/befriending their potential, not their reality. You see who they 'could be' if they just tried harder, listened to you, changed this one thing. But people aren't renovation projects. You can't love someone into changing. Either accept them exactly as they are right now, or leave. This fantasy version you're in love with? They don't exist.",
    challenge: "The Reality Check: Write down the top three things you wish someone in your life would change. Now answer honestly: If they NEVER change these things, can you accept them? If not, you're in love with a fantasy, not a person.",
    morningPrompt: "Today I will interact with people based on who they are, not who I hope they'll become.",
    eveningPrompt: "Answer these three questions:\n1. Where did I try to coach, fix, or change someone instead of accepting them?\n2. What relationship am I staying in based on potential rather than reality?\n3. How is my need to 'improve' others actually about my own control issues?",
    winsTitle: "One person I accepted completely as they are:"
  },
  {
    day: 17,
    week: 3,
    track: "Relationships",
    title: "The Vulnerability Allergy: Your Walls Are Keeping Everything Out",
    description: "The Vulnerability Allergy: Your Walls Are Keeping Everything Out",
    quote: { text: "No man is an island, entire of itself; every man is a piece of the continent.", author: "Marcus Aurelius" },
    broTranslation: "You've been hurt, so now you're Fort Knox. No one gets in. You share nothing real, need nobody, trust no one. You think you're strong but you're just scared. Those walls you built to keep pain out are also keeping love out. You're so protected that you're alone. Being invulnerable isn't strength - it's a prison you built yourself.",
    challenge: "The Wall Drop: Share something real and uncomfortable with someone today. Not your usual surface stuff - something that makes you feel exposed. Watch how connection deepens when you stop performing strength.",
    morningPrompt: "Today I will let someone see me struggle instead of always having it together.",
    eveningPrompt: "Answer these three questions:\n1. Where did my need to appear strong prevent real connection?\n2. What would people be surprised to know I'm struggling with?\n3. How is my fear of being seen as weak making me weaker?",
    winsTitle: "One moment of genuine vulnerability:"
  },
  {
    day: 18,
    week: 3,
    track: "Relationships",
    title: "The Comparison Trap: Their Love Doesn't Diminish Yours",
    description: "The Comparison Trap: Their Love Doesn't Diminish Yours",
    quote: { text: "It is not death that a man should fear, but never beginning to live.", author: "Marcus Aurelius" },
    broTranslation: "You're jealous of the attention others get, the love they receive, the relationships they have. You think there's a limited amount of love in the world and them getting some means less for you. But love isn't pie. Someone else being loved doesn't make you less loveable. Your jealousy is just your insecurity in a costume.",
    challenge: "The Celebration Test: Today, genuinely celebrate someone else's relationship win. Their engagement, their happiness, their connection. Feel the resistance in your body to being happy for them. That resistance is your work.",
    morningPrompt: "Today I will remember that someone else's happiness doesn't steal from mine.",
    eveningPrompt: "Answer these three questions:\n1. When did jealousy over someone else's relationship poison my own peace?\n2. What insecurity of mine gets triggered when others receive love?\n3. How does comparing my relationships to others blind me to what I have?",
    winsTitle: "One person's success I genuinely celebrated:"
  },
  {
    day: 19,
    week: 3,
    track: "Relationships",
    title: "The Ghost Protocol: Closure Is Something You Give Yourself",
    description: "The Ghost Protocol: Closure Is Something You Give Yourself",
    quote: { text: "You have power over your mind - not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius" },
    broTranslation: "You're waiting for them to explain why they left, apologize for the hurt, give you 'closure.' News flash: they're not coming. And even if they did, it wouldn't fix what you think it would. Closure isn't something someone gives you - it's something you give yourself. Stop waiting for permission to move on. Their silence IS your answer.",
    challenge: "The Closure Creation: Write yourself the apology or explanation you're waiting for from someone else. Write what you need to hear. Then realize you just gave yourself what you've been begging them for.",
    morningPrompt: "Today I will stop waiting for answers from people who've already shown me who they are through their actions.",
    eveningPrompt: "Answer these three questions:\n1. What explanation am I waiting for that wouldn't actually change anything?\n2. How is my need for closure keeping me stuck in the past?\n3. What answer could they possibly give that would make their actions okay?",
    winsTitle: "One piece of closure I gave myself:"
  },
  {
    day: 20,
    week: 3,
    track: "Relationships",
    title: "The Authenticity Test: Stop Curating, Start Living",
    description: "The Authenticity Test: Stop Curating, Start Living",
    quote: { text: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius" },
    broTranslation: "Your relationships are performances. You show the highlight reel, hide the struggles, curate your personality based on who's watching. But people can't love who you really are if you never show them. You're getting validation for a character you're playing, not for you. The exhaustion you feel? That's the weight of maintaining all these fake versions of yourself.",
    challenge: "The Real Post: Share something messy and real with someone today. Not humble-bragging or fishing for compliments - actual vulnerability. Your struggle, your failure, your fear. Let them see the human, not the highlight.",
    morningPrompt: "Today I will be myself even if it costs me approval.",
    eveningPrompt: "Answer these three questions:\n1. Where did I perform a version of myself instead of being authentic?\n2. What part of my real self am I hiding from the people closest to me?\n3. How is my need to be perfect preventing people from actually knowing me?",
    winsTitle: "One moment I chose to be real instead of perfect:"
  },
  {
    day: 21,
    week: 3,
    track: "Relationships",
    title: "The Energy Vampire Detection: Not Everyone Deserves Access",
    description: "The Energy Vampire Detection: Not Everyone Deserves Access",
    quote: { text: "How long are you going to wait before you demand the best for yourself?", author: "Epictetus" },
    broTranslation: "Some people only hit you up when they need something. They dump their problems, take your energy, then disappear until the next crisis. You're not a therapist, ATM, or emotional dumping ground. These energy vampires will drain you dry if you let them. It's not mean to protect your energy - it's necessary. Not everyone deserves access to you.",
    challenge: "The Access Audit: List everyone who has your phone number. Put a star next to those who only contact you when they need something. Those stars? That's where you need boundaries. Today, don't respond immediately to any starred names.",
    morningPrompt: "Today I will protect my energy like the finite resource it is.",
    eveningPrompt: "Answer these three questions:\n1. Who drained my energy today without giving anything back?\n2. What relationship is all take and no give?\n3. Where did I allow someone to use me because I'm afraid of being seen as mean?",
    winsTitle: "One energy vampire I put a boundary on:"
  },
  {
    day: 22,
    week: 4,
    track: "Relationships",
    title: "The Love Language Lie: Stop Expecting Them to Love Like You",
    description: "The Love Language Lie: Stop Expecting Them to Love Like You",
    quote: { text: "When you wake up in the morning, tell yourself: The people I deal with today will be meddling, ungrateful, arrogant, dishonest, jealous, and surly.", author: "Marcus Aurelius" },
    broTranslation: "You're pissed because they don't love you the way YOU would love you. They don't express it right, don't show it how you need, don't speak your language. But maybe they're screaming 'I love you' in their own language and you're too busy being disappointed to hear it. Stop demanding people love you in your style. Learn to recognize love in all its forms.",
    challenge: "The Translation Exercise: Think of someone whose love you doubt. Write down three ways they might be showing love that you're not recognizing because it's not how YOU would do it. Look for their love, not your version of it.",
    morningPrompt: "Today I will recognize expressions of love that don't match my expectations.",
    eveningPrompt: "Answer these three questions:\n1. What expression of care did I dismiss because it wasn't in my preferred style?\n2. How did my rigid expectations of how love 'should' look blind me to how it actually appears?\n3. Where did I reject someone's best effort because it wasn't perfect?",
    winsTitle: "One alternate 'love language' I recognized:"
  },
  {
    day: 23,
    week: 4,
    track: "Relationships",
    title: "The Trigger Map: Your Reactions Are About You",
    description: "The Trigger Map: Your Reactions Are About You",
    quote: { text: "You always own the option of having no opinion. There is never any need to get worked up or to trouble your soul about things you can't control.", author: "Marcus Aurelius" },
    broTranslation: "When someone pushes your buttons, those buttons were already there. They didn't install them - your past did. Your explosive reactions, your instant rage, your immediate hurt - that's your unhealed shit getting activated. Stop blaming people for triggering you and start asking why those triggers exist. They're showing you where you still need work.",
    challenge: "The Trigger Timeline: When you get triggered today, stop and ask: 'When have I felt this exact feeling before?' Trace it back. Usually, it's not about the present moment - it's about something old getting reactivated.",
    morningPrompt: "Today I will own my triggers instead of blaming others for pushing my buttons.",
    eveningPrompt: "Answer these three questions:\n1. What reaction did I have today that was disproportionate to what actually happened?\n2. Which of my responses was more about my past than the present situation?\n3. What trigger showed me where I still have healing to do?",
    winsTitle: "One trigger I mapped to its source:"
  },
  {
    day: 24,
    week: 4,
    track: "Relationships",
    title: "The Conflict Avoidance: Peace at Any Price Is Too Expensive",
    description: "The Conflict Avoidance: Peace at Any Price Is Too Expensive",
    quote: { text: "Speak the truth as you see it. But with kindness. With humility. Without hypocrisy.", author: "Marcus Aurelius" },
    broTranslation: "You're so conflict-avoidant that you're living in fake relationships. You agree when you disagree, smile when you're hurt, say 'it's fine' when it's not. But avoiding conflict doesn't create peace - it creates resentment. Those fights you're avoiding don't disappear; they go underground and poison everything. Sometimes conflict is the path to real peace.",
    challenge: "The Conflict Courage: Address one issue you've been avoiding in a relationship. Not aggressively, but honestly. 'Hey, can we talk about X? It's been bothering me.' Feel how scary but necessary it is.",
    morningPrompt: "Today I will have a difficult conversation I've been avoiding instead of letting resentment build.",
    eveningPrompt: "Answer these three questions:\n1. What conflict did I avoid that's now growing bigger in silence?\n2. Where did my fear of confrontation create a fake peace?\n3. How is my conflict avoidance slowly killing my relationships?",
    winsTitle: "One difficult conversation I had:"
  },
  {
    day: 25,
    week: 4,
    track: "Relationships",
    title: "The Availability Addiction: Being Busy Isn't Being Important",
    description: "The Availability Addiction: Being Busy Isn't Being Important",
    quote: { text: "If you seek tranquility, do less. Or more accurately, do what's essential.", author: "Marcus Aurelius" },
    broTranslation: "You answer every text immediately, always available, always 'on.' You think this makes you a good friend/partner. But really? You're training people that you have no life, no boundaries, no priorities. Being constantly available doesn't make you valuable - it makes you common. Scarcity creates value, even in relationships.",
    challenge: "The Response Delay: Today, wait at least 30 minutes before responding to non-urgent messages. Notice how the world doesn't end. Notice how people start respecting your time more when you respect it first.",
    morningPrompt: "Today I will not be instantly available to everyone who wants my attention.",
    eveningPrompt: "Answer these three questions:\n1. Where did my instant availability actually diminish my value in someone's eyes?\n2. What boundaries around my time do I need to establish?\n3. How does being always available prevent me from being fully present anywhere?",
    winsTitle: "One time I prioritized my time over instant availability:"
  },
  {
    day: 26,
    week: 4,
    track: "Relationships",
    title: "The Loyalty Trap: Some Bridges Need to Burn",
    description: "The Loyalty Trap: Some Bridges Need to Burn",
    quote: { text: "Associate with people who are likely to improve you. Welcome those whom you are capable of improving.", author: "Seneca" },
    broTranslation: "You're holding onto toxic relationships because of history. 'We've been friends for 10 years' or 'But they're family.' Length of relationship doesn't equal quality. Some people are meant to be chapters, not the whole book. Your misplaced loyalty to people who consistently hurt you isn't noble - it's self-harm. Some bridges don't need rebuilding; they need to stay burned.",
    challenge: "The Relationship ROI: Write down your five closest relationships. Next to each, honestly assess: Does this relationship add to or subtract from my life? If it's been subtracting for years, why are you still investing?",
    morningPrompt: "Today I will stop using history as an excuse to maintain toxic relationships.",
    eveningPrompt: "Answer these three questions:\n1. What relationship am I maintaining out of obligation rather than genuine connection?\n2. Where is my loyalty to others overriding my loyalty to myself?\n3. Which bridge do I keep trying to rebuild that should stay burned?",
    winsTitle: "One relationship I re-evaluated:"
  },
  {
    day: 27,
    week: 4,
    track: "Relationships",
    title: "The Feedback Filter: Not All Criticism Is Created Equal",
    description: "The Feedback Filter: Not All Criticism Is Created Equal",
    quote: { text: "How much trouble he avoids who does not look to see what his neighbor says or does.", author: "Marcus Aurelius" },
    broTranslation: "You're taking feedback from people who haven't done shit with their lives. You're letting someone who can't maintain a relationship tell you about love. You're accepting criticism from people you wouldn't go to for advice. Consider the source. If they haven't built what you're building, their blueprint is worthless.",
    challenge: "The Source Check: Today, when someone offers criticism or advice, ask yourself: 'Would I trade places with this person?' If no, their opinion holds no weight. Thank them and move on.",
    morningPrompt: "Today I will only accept criticism from people whose lives I respect.",
    eveningPrompt: "Answer these three questions:\n1. Whose opinion affected me today who hasn't earned the right to that influence?\n2. What criticism did I internalize from someone who isn't qualified to give it?\n3. How often do I value the opinions of people I don't actually admire?",
    winsTitle: "One piece of feedback I chose to discard:"
  },
  {
    day: 28,
    week: 4,
    track: "Relationships",
    title: "The Rejection Story: It's Information, Not Confirmation",
    description: "The Rejection Story: It's Information, Not Confirmation",
    quote: { text: "What is to give light must endure burning.", author: "Viktor Frankl" },
    broTranslation: "Someone rejected you and you made it mean you're worthless. They didn't text back and you decided you're unlovable. They chose someone else and you confirmed your worst fears about yourself. But rejection isn't confirmation of your unworthiness - it's information about compatibility. Their 'no' isn't about your value; it's about fit. Stop making their preferences mean something about your worth.",
    challenge: "The Rejection Reframe: Write down a recent rejection. Now write three reasons it might have happened that have nothing to do with your worth. Their issues, their preferences, their journey. Separate their choice from your value.",
    morningPrompt: "Today I will see rejection as redirection, not confirmation of my fears.",
    eveningPrompt: "Answer these three questions:\n1. What story did I create about a rejection that was unnecessarily harsh on myself?\n2. How did I make someone else's preference mean something about my worth?\n3. Where did I take something personally that wasn't actually personal?",
    winsTitle: "One rejection I reframed:"
  },
  {
    day: 29,
    week: 4,
    track: "Relationships",
    title: "The Connection Currency: Presence Is the Only Real Gift",
    description: "The Connection Currency: Presence Is the Only Real Gift",
    quote: { text: "At every moment keep a sturdy mind on the task at hand, as a Roman and human being, doing it with strict and simple dignity, affection, freedom, and justice.", author: "Marcus Aurelius" },
    broTranslation: "You're physically there but mentally everywhere else. Scrolling while they talk, planning your response instead of listening, thinking about work during dinner. You think you're efficient, multitasking life. But you're missing everything. The people in your life don't need your gifts, your money, or your achievements. They need your presence. Actually being there is the rarest gift you can give.",
    challenge: "The Phone Down Challenge: During every in-person interaction today, put your phone completely away. Not face down - away. Give people your full presence and watch how differently they respond to you.",
    morningPrompt: "Today I will be fully present in my interactions instead of physically there but mentally absent.",
    eveningPrompt: "Answer these three questions:\n1. When was I physically present but mentally absent today?\n2. What moment did I miss because I was distracted by past or future?\n3. How did my lack of presence affect the quality of my connections?",
    winsTitle: "One interaction where I was fully present:"
  },
  {
    day: 30,
    week: 4,
    track: "Relationships",
    title: "The Graduate Lesson: You've Always Had the Power",
    description: "The Graduate Lesson: You've Always Had the Power",
    quote: { text: "Every new beginning comes from some other beginning's end.", author: "Seneca" },
    broTranslation: "Here's what 30 days taught you: Every relationship problem you have is actually a you problem. Not because you're broken, but because you're the only variable you control. You can't make them love you right, communicate better, or stop being toxic. But you can change how you show up, what you accept, and where you place your energy. The power was never in changing them - it was always in changing you.",
    challenge: "The Integration Inventory: Write down the three biggest insights from this month. Next to each, write one concrete action you'll take going forward. This isn't the end - it's the beginning of you showing up differently.",
    morningPrompt: "Today I will own my power to transform my relationships by transforming myself.",
    eveningPrompt: "Answer these three questions:\n1. What pattern did I break this month that I'm committed to not returning to?\n2. How have my relationships already shifted from the work I've done on myself?\n3. What person do I need to become to have the relationships I want?",
    winsTitle: "One way I'll continue to own my power:"
  }
];
